#!/bin/sh

set -ue

FAIL=
fail () {
	FAIL="$FAIL $*"
}
check_fail () {
	if [ -n "$FAIL" ]; then
		echo " *** Checks failed: $FAIL"
		echo " *** Commit aborted! ***"
		exit 1
	fi
}

# find files affected by commit
# exclude deleted files
FILES=`(git diff --cached --name-only --diff-filter=A; git diff --cached --name-only) |\
	egrep '\.cgi$|\.pl$|\.t$|\.pm$|\.psgi$' | sort -u `
# echo "Commit (w/deleted): $FILES"

FILES=`for i in $FILES; do [ -f "$i" ] && echo "$i"; done`
echo "Checking files: $FILES"

# check selected files
for i in $FILES; do
	echo "$i"
	perl -wne '/\s\n/ and exit 1' "$i" || fail "$i" - "Spaces at EOL"
	perlcritic "$i" || fail "$i" - "Perl critic"

  CHECK_ONLY='-c'
	echo "$i" | egrep -q '\.pm$' && CHECK_ONLY=''

  SYNTAX="$(perl -Mwarnings=FATAL,all -Mstrict -Ilib -Ilib/perl5 -w $CHECK_ONLY "$i" 2>&1)"
  if [ ! -z "$SYNTAX" ] && [ "$SYNTAX" != "$i syntax OK" ]; then
    echo >&2 "<syntax $i>\n$SYNTAX\n</syntax>"
    fail "$i" - Strict
  fi
done

check_fail

prove -Ilib -r t xt || fail "tests fail"

check_fail
